### ISSUE TITLE
Allow using different licenses for advisories

### ISSUE THREAD

**Issue by amousset** [rustsec/advisory-db#1409]
As discussed on Zulip previously, adding the ability to provide a specific license and attribution for advisories would be useful, especially to allow importing advisories from Github Security Database (under CC-BY 4.0).

This would require at least:

* Decide which licenses we want to allow (limiting to CC-0 or CC-BY for now is probably better)
* Two new optional metadata fields in advisories, something like:

```toml
license = "CC-BY-4.0" # using spdx identifiers like in Cargo.toml, CC0-1.0 by default
attribution = ["Advisory Author <author@example.com>"] # empty by default, not required for CC0-1.0
```

* Support for these fields in rustsec lib
* Displaying these fields in advisory details on rustsec.org
* Checking impact on OSV export (the OSV schema contains `credits` fields but nothing for license it seems, and currently RustSec is [documented](https://github.com/google/osv.dev#current-data-sources) as CC-0)
* ... something else?
