### ISSUE TITLE
Whitelisting non-vulnerable usages / false positives in advisories

### ISSUE THREAD

**Issue by tarcieri** [rustsec/advisory-db#288]
This came up via: https://github.com/clap-rs/clap/issues/1569

The specific case is `clap` is pulling in `rust-yaml` which has [RUSTSEC-2018-0006](https://rustsec.org/advisories/RUSTSEC-2018-0006.html). They use the vulnerable API, but not in a way that triggers the vulnerability.

I've suggested updating the advisory to note their usage isn't vulnerable, but it'd be nice to be able to specify this programmatically somehow.

Something like:

```toml
[unaffected_consumers]
clap = ["2"]
```

**Comment by kbknapp** [comment]
Much appreciated! Just off the top of my head, maybe you'd probably want `unaffected consumers` to require a full version spec? In case the consumer has an update and starts using the vulnerability for real. It's more work to have to update the table to the new version being consumed, but ultimately its for the right reason to keep false negatives away which IMO are worse than false positives.

**Comment by ckaran** [comment]
```toml
[unaffected_consumers]
clap = ["2"]
```

You might want to force this to go all the way out to the patch level; right now it looks like all of version 2 is unaffected (which is *currently* correct for clap), but they could add a new non-breaking minor release that is affected.  I do like that it's a list though!

**Comment by CreepySkeleton** [comment]
And maybe require attaching a bit of context
```toml
[unaffected_consumers]
clap = { version = ["2"], reason = "never triggers, only trusted input", discussion = "link to thread" }
```

Where `reason` is a summary of why this is not a vulnerability and the `discussion` link is self evident.
